# Generated by Django 4.1.7 on 2023-03-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='sneakers_image', verbose_name='Изаброжение')),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nike')),
            ],
        ),
    ]
